#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Blackcat Informatics® Inc.
# SPDX-License-Identifier: MIT

set -euo pipefail

password="${VALKEY_PASSWORD:-}"
if [[ -z "${password}" && -n "${VALKEY_PASSWORD_FILE:-}" && -r "${VALKEY_PASSWORD_FILE}" ]]; then
  password=$(<"${VALKEY_PASSWORD_FILE}")
fi

if [[ -z "${password}" ]]; then
  echo "[valkey] ERROR: password not provided via VALKEY_PASSWORD or VALKEY_PASSWORD_FILE" >&2
  exit 1
fi

export VALKEY_PASSWORD="${password}"
export VALKEY_PORT=${VALKEY_PORT:-6379}
export VALKEY_APPENDONLY=${VALKEY_APPENDONLY:-yes}
export VALKEY_MAXMEMORY=${VALKEY_MAXMEMORY:-256mb}
export VALKEY_MAXMEMORY_POLICY=${VALKEY_MAXMEMORY_POLICY:-allkeys-lru}
export VALKEY_DATABASES=${VALKEY_DATABASES:-16}

umask 077
cat > /data/valkey.conf <<EOF
# Generated by core_data
bind 0.0.0.0
protected-mode no
port ${VALKEY_PORT}
requirepass ${VALKEY_PASSWORD}
appendonly ${VALKEY_APPENDONLY}
appendfsync everysec
save 900 1
save 300 10
save 60 10000
maxmemory ${VALKEY_MAXMEMORY}
maxmemory-policy ${VALKEY_MAXMEMORY_POLICY}
dir /data
databases ${VALKEY_DATABASES}
logfile ""
rename-command CONFIG ""
rename-command SHUTDOWN ""
EOF
unset VALKEY_PASSWORD
exec /usr/local/bin/valkey-server /data/valkey.conf
