#!/bin/sh
# SPDX-FileCopyrightText: 2025 Blackcat Informatics® Inc.
# SPDX-License-Identifier: MIT

set -eu

password=${VALKEY_PASSWORD:-}
if [ -z "${password}" ] && [ -n "${VALKEY_PASSWORD_FILE:-}" ] && [ -r "${VALKEY_PASSWORD_FILE}" ]; then
  password=$(cat "${VALKEY_PASSWORD_FILE}")
fi

if [ -z "${password}" ]; then
  echo "[valkey] ERROR: password not provided via VALKEY_PASSWORD or VALKEY_PASSWORD_FILE" >&2
  exit 1
fi

export VALKEY_PASSWORD="${password}"
export VALKEY_PORT="${VALKEY_PORT:-6379}"
export VALKEY_APPENDONLY="${VALKEY_APPENDONLY:-yes}"
export VALKEY_MAXMEMORY="${VALKEY_MAXMEMORY:-256mb}"
export VALKEY_MAXMEMORY_POLICY="${VALKEY_MAXMEMORY_POLICY:-allkeys-lru}"
export VALKEY_DATABASES="${VALKEY_DATABASES:-16}"
data_dir=${VALKEY_DATA_DIR:-/data}

config_path=${VALKEY_CONFIG_PATH:-${data_dir}/valkey.conf}
if ! touch "${config_path}" 2>/dev/null; then
  echo "[valkey] WARNING: unable to write to ${config_path}, falling back to /tmp/valkey.conf" >&2
  config_path="/tmp/valkey.conf"
  data_dir="/tmp"
  if ! touch "${config_path}" 2>/dev/null; then
    echo "[valkey] ERROR: unable to write to fallback config path ${config_path}. Exiting." >&2
    exit 1
  fi
fi

umask 077
cat > "${config_path}" <<EOF
# Generated by core_data
bind 0.0.0.0
protected-mode no
port ${VALKEY_PORT}
requirepass ${VALKEY_PASSWORD}
appendonly ${VALKEY_APPENDONLY}
appendfsync everysec
save 900 1
save 300 10
save 60 10000
maxmemory ${VALKEY_MAXMEMORY}
maxmemory-policy ${VALKEY_MAXMEMORY_POLICY}
dir ${data_dir}
appendfilename appendonly.aof
databases ${VALKEY_DATABASES}
logfile ""
rename-command CONFIG ""
rename-command SHUTDOWN ""
EOF
unset VALKEY_PASSWORD
exec /usr/local/bin/valkey-server "${config_path}"
