# SPDX-FileCopyrightText: 2025 Blackcat Informatics® Inc.
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run core_data smoke workflow
        run: python -m pytest -k full_workflow

      - name: Upload generated backups
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backups
          path: backups
          if-no-files-found: ignore
